import { sql } from 'drizzle-orm';
import { db } from './db';
import { vendorItems } from './db/schema';

export async function seedDirectory() {
  // Idempotent: skip if already seeded
  const existing = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(vendorItems);

  if ((existing[0]?.count ?? 0) > 0) {
    return;
  }

  const venues = [
    {
      section: 'venue' as const,
      vendorCategory: 'hall',
      title: 'Al-Noor Banquet Hall',
      location: 'London, UK',
      priceRange: '£££',
      description: 'Elegant banquet hall with a capacity of 500 guests, perfect for large Nikkah ceremonies.',
      bio: 'Al-Noor Banquet Hall has been the premier choice for Muslim weddings in London for over 15 years. Our dedicated team ensures every detail of your special day is handled with care and cultural sensitivity.',
      capacity: '500',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Stage', 'Sound System', 'Lighting', 'Bridal Room', 'Halal Kitchen'],
      amenities: ['Kitchen', 'Parking Lot', 'Wheelchair Ramp'],
      contactEmail: 'events@alnoorhall.co.uk',
      contactPhone: '+44 20 7946 0123',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'mosque',
      title: 'East London Mosque',
      location: 'Whitechapel, London',
      priceRange: '£',
      description: 'Beautiful mosque venue with separate prayer halls for a traditional Nikkah ceremony.',
      bio: 'One of the largest mosques in the UK, East London Mosque offers a serene and spiritual setting for your Nikkah. Our experienced staff coordinate with families to ensure a smooth, blessed ceremony.',
      capacity: '300',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Prayer Hall', 'Courtyard', 'Wudu Facilities', 'Separate Sisters Section'],
      amenities: ['Wudu Area', 'Parking'],
      contactEmail: 'bookings@eastlondonmosque.org.uk',
      contactPhone: '+44 20 7650 3000',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'hotel',
      title: 'The Savoy',
      location: 'Central London',
      priceRange: '£££',
      description: 'Luxury hotel ballroom with stunning chandeliers and premium catering.',
      bio: 'The Savoy has hosted the most prestigious events for over a century. Our Lancaster Ballroom provides an unmatched backdrop for your Walima reception, with bespoke halal menu options available.',
      capacity: '400',
      sisterFriendly: false,
      parking: true,
      disabilityAccessible: true,
      features: ['Ballroom', 'Bridal Suite', 'Valet Parking', 'River View'],
      amenities: ['Full Kitchen', 'AV Equipment', 'Coat Check'],
      contactEmail: 'weddings@thesavoy.com',
      contactPhone: '+44 20 7836 4343',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'hall',
      title: 'Ummah Community Centre',
      location: 'Birmingham, UK',
      priceRange: '££',
      description: 'Spacious community centre in the heart of Birmingham, accommodating up to 350 guests.',
      bio: 'A welcoming community space that has been the venue of choice for hundreds of Nikkah ceremonies. Flexible layout options and on-site catering coordination make planning stress-free.',
      capacity: '350',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Main Hall', 'Kitchen Access', 'Stage', 'PA System'],
      amenities: ['Tables & Chairs', 'Sound System'],
      contactEmail: 'bookings@ummahcentre.co.uk',
      contactPhone: '+44 121 456 7890',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'hall',
      title: 'Crescent Moon Events',
      location: 'Manchester, UK',
      priceRange: '£££',
      description: 'Modern event space with customisable lighting and decor packages.',
      bio: 'Crescent Moon Events specialises in creating magical atmospheres for Muslim weddings. Our in-house design team works with you to bring your vision to life with bespoke décor and lighting.',
      capacity: '250',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['LED Lighting', 'Dance Floor', 'Lounge Area', 'Photo Backdrop'],
      amenities: ['In-House Catering', 'Valet'],
      contactEmail: 'hello@crescentmoonevents.co.uk',
      contactPhone: '+44 161 234 5678',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'hotel',
      title: 'Hilton Park Lane',
      location: 'Mayfair, London',
      priceRange: '£££',
      description: 'Premium Mayfair hotel with multiple ballroom options and stunning views.',
      bio: 'Located in the heart of Mayfair, the Hilton Park Lane offers world-class service and breathtaking views of Hyde Park. Our dedicated wedding coordinators specialise in culturally sensitive celebrations.',
      capacity: '600',
      sisterFriendly: false,
      parking: true,
      disabilityAccessible: true,
      features: ['Multiple Rooms', 'Bridal Suite', 'Park Views', 'Red Carpet Entrance'],
      amenities: ['Full Catering', 'AV', 'Valet'],
      contactEmail: 'events@hiltonparklane.com',
      contactPhone: '+44 20 7493 8000',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'mosque',
      title: 'Birmingham Central Mosque',
      location: 'Highgate, Birmingham',
      priceRange: '£',
      description: 'Welcoming mosque with a large community hall for intimate ceremonies.',
      bio: 'Birmingham Central Mosque is one of the earliest purpose-built mosques in the UK. Our community hall is perfect for traditional Nikkah ceremonies with full imam services available.',
      capacity: '150',
      sisterFriendly: true,
      parking: false,
      disabilityAccessible: true,
      features: ['Community Hall', 'Kitchen', 'Garden Area'],
      amenities: ['Wudu Facilities'],
      contactEmail: 'info@centralmosque.org.uk',
      contactPhone: '+44 121 440 5355',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'hall',
      title: 'Salam Palace',
      location: 'Bradford, UK',
      priceRange: '££',
      description: 'Affordable banquet hall with halal catering options included.',
      bio: 'Salam Palace has been serving the Bradford community for over a decade. We offer all-inclusive wedding packages with authentic halal catering, décor, and entertainment coordination.',
      capacity: '300',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Stage', 'Projector Screen', 'Separate Sections Available'],
      amenities: ['Halal Kitchen', 'Free Parking'],
      contactEmail: 'events@salampalace.co.uk',
      contactPhone: '+44 1274 567 890',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'hotel',
      title: 'Royal Lancaster London',
      location: 'Bayswater, London',
      priceRange: '£££',
      description: 'Iconic hotel overlooking Hyde Park with a grand ballroom for up to 700 guests.',
      bio: 'The Royal Lancaster London has been a landmark venue for prestigious celebrations since 1967. Our Nine Kings Suite offers panoramic views of Hyde Park and our events team has extensive experience coordinating Muslim weddings with bespoke halal menus.',
      capacity: '700',
      sisterFriendly: false,
      parking: true,
      disabilityAccessible: true,
      features: ['Grand Ballroom', 'Hyde Park Views', 'Bridal Suite', 'Multiple Event Rooms'],
      amenities: ['Full Catering', 'Valet Parking', 'AV Equipment'],
      contactEmail: 'events@royallancaster.com',
      contactPhone: '+44 20 7551 6000',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'mosque',
      title: 'Manchester Central Mosque',
      location: 'Victoria Park, Manchester',
      priceRange: '£',
      description: 'One of the largest mosques in the North, offering a beautiful setting for traditional Nikkah ceremonies.',
      bio: 'Manchester Central Mosque serves one of the largest Muslim communities in the North of England. Our main hall provides a dignified and spiritual atmosphere for Nikkah ceremonies, with experienced imams available to officiate.',
      capacity: '200',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Main Prayer Hall', 'Community Room', 'Separate Sisters Section', 'Garden'],
      amenities: ['Wudu Facilities', 'Free Parking'],
      contactEmail: 'admin@manchestercentralmosque.org',
      contactPhone: '+44 161 226 7171',
    },
    {
      section: 'venue' as const,
      vendorCategory: 'mosque',
      title: 'Edinburgh Central Mosque',
      location: 'Potterrow, Edinburgh',
      priceRange: '£',
      description: 'Stunning mosque with Islamic architecture, ideal for intimate Nikkah ceremonies.',
      bio: 'Edinburgh Central Mosque is one of Scotland\'s most beautiful Islamic buildings. The tranquil setting and striking architecture provide a memorable backdrop for your Nikkah, with full imam services and coordination support.',
      capacity: '120',
      sisterFriendly: true,
      parking: false,
      disabilityAccessible: true,
      features: ['Prayer Hall', 'Meeting Rooms', 'Courtyard', 'Islamic Architecture'],
      amenities: ['Wudu Facilities', 'Kitchen Access'],
      contactEmail: 'info@edinburghmosque.org',
      contactPhone: '+44 131 667 1777',
    },
  ];

  const vendors = [
    {
      section: 'vendor' as const,
      vendorCategory: 'photographer',
      title: 'Noor Photography',
      location: 'London, UK',
      priceRange: '£££',
      description: 'Specialising in elegant Muslim wedding photography with a focus on modesty.',
      bio: 'Noor Photography has captured over 500 Muslim weddings across the UK. We understand the cultural nuances and work sensitively with families to document every precious moment while respecting boundaries.',
      specialty: 'Muslim Wedding Photography',
      sisterFriendly: true,
      features: ['Full Day Coverage', 'Engagement Shoots', 'Albums Included', 'Female Photographer Available'],
      contactEmail: 'bookings@noorphotography.co.uk',
      contactPhone: '+44 7700 900123',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'caterer',
      title: 'Bismillah Catering',
      location: 'Birmingham, UK',
      priceRange: '££',
      description: 'Premium halal catering with South Asian, Middle Eastern, and fusion menus.',
      bio: 'Family-run halal catering service with 20 years of experience. We source all our meat from HMC-certified suppliers and offer tasting sessions before your big day.',
      specialty: 'Halal Catering',
      features: ['Tasting Sessions', 'Custom Menus', 'Live Cooking Stations', 'HMC Certified'],
      contactEmail: 'orders@bismillahcatering.co.uk',
      contactPhone: '+44 121 789 0123',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'decorator',
      title: 'Zahra Floral Design',
      location: 'Manchester, UK',
      priceRange: '££',
      description: 'Custom floral arrangements inspired by Islamic geometric patterns.',
      bio: 'Zahra Floral Design creates breathtaking arrangements that blend traditional Islamic aesthetics with contemporary design. From centrepieces to full venue transformations, we bring your vision to life.',
      specialty: 'Wedding Florals & Décor',
      features: ['Venue Styling', 'Centrepieces', 'Bridal Bouquets', 'Stage Decoration'],
      contactEmail: 'hello@zahraflorals.co.uk',
      contactPhone: '+44 161 456 7890',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'dj',
      title: 'Nasheed Beats Entertainment',
      location: 'London, UK',
      priceRange: '££',
      description: 'Halal entertainment with nasheeds, live daff, and clean music DJing.',
      bio: 'Nasheed Beats brings energy and joy to your celebration while keeping it halal. Our team of performers includes daff players, nasheed artists, and DJs who specialise in clean entertainment.',
      specialty: 'Islamic Entertainment',
      features: ['Live Daff', 'Nasheed Artists', 'Clean DJ Sets', 'Sound & Lighting'],
      contactEmail: 'bookings@nasheedbeats.co.uk',
      contactPhone: '+44 7700 900456',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'photographer',
      title: 'Barakah Films',
      location: 'Leeds, UK',
      priceRange: '£££',
      description: 'Cinematic wedding films capturing every beautiful moment of your nikkah.',
      bio: 'Barakah Films produces cinematic highlight reels and full-length wedding films. Our team is experienced in filming at mosques, halls, and outdoor venues with a respectful, unobtrusive approach.',
      specialty: 'Wedding Videography',
      features: ['Highlight Reel', 'Full Ceremony Film', 'Drone Footage', 'Same-Day Edit'],
      contactEmail: 'info@barakahfilms.co.uk',
      contactPhone: '+44 113 234 5678',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'mua',
      title: 'Hijabi Glam Studio',
      location: 'London, UK',
      priceRange: '££',
      description: 'Bridal makeup and hijab styling for your perfect day.',
      bio: 'Hijabi Glam Studio is run by an all-female team specialising in bridal looks that complement your hijab style. We offer trials, on-location services, and bridal party packages.',
      specialty: 'Bridal Makeup & Hijab Styling',
      sisterFriendly: true,
      features: ['Bridal Trials', 'On-Location Service', 'Hijab Styling', 'Bridal Party Packages'],
      contactEmail: 'bookings@hijabiglam.co.uk',
      contactPhone: '+44 7700 900789',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'caterer',
      title: 'Saffron & Spice Catering',
      location: 'London, UK',
      priceRange: '£££',
      description: 'Upscale halal catering featuring diverse international cuisines.',
      bio: 'Saffron & Spice brings Michelin-level presentation to halal catering. Our executive chef trained at Le Cordon Bleu and creates fusion menus that wow guests while staying true to halal standards.',
      specialty: 'International Halal Cuisine',
      features: ['Chef\'s Table Experience', 'Fusion Menus', 'Dessert Bars', 'Premium Presentation'],
      contactEmail: 'events@saffronandspice.co.uk',
      contactPhone: '+44 20 3456 7890',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'photographer',
      title: 'Amanah Studios',
      location: 'Birmingham, UK',
      priceRange: '££',
      description: 'Photography and photo booth services for Muslim weddings.',
      bio: 'Amanah Studios provides affordable, high-quality photography for Muslim weddings. We also offer fun photo booth packages with Islamic-themed props that guests love.',
      specialty: 'Event Photography',
      sisterFriendly: true,
      features: ['Photo Booth', 'Prints On-Site', 'Digital Gallery', 'Female Photographer'],
      contactEmail: 'hello@amanahstudios.co.uk',
      contactPhone: '+44 121 345 6789',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'decorator',
      title: 'Henna & Drapes Decor',
      location: 'Bradford, UK',
      priceRange: '££',
      description: 'Full event styling with draping, centrepieces, and henna-themed decor.',
      bio: 'Henna & Drapes transforms any venue into a magical space. From elaborate stage backdrops to intimate table settings, our team handles every decorative detail for your Nikkah and Walima.',
      specialty: 'Wedding Décor',
      features: ['Stage Backdrops', 'Ceiling Draping', 'Table Settings', 'Flower Walls'],
      contactEmail: 'info@hennaanddrapes.co.uk',
      contactPhone: '+44 1274 890 123',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'caterer',
      title: 'Baraka Bakery',
      location: 'Leicester, UK',
      priceRange: '££',
      description: 'Custom wedding cakes and dessert tables, all halal certified.',
      bio: 'Baraka Bakery creates stunning wedding cakes that taste as incredible as they look. All ingredients are halal and we offer egg-free and dairy-free options. Free tasting sessions for all wedding bookings.',
      specialty: 'Halal Wedding Cakes',
      features: ['Custom Designs', 'Dessert Tables', 'Halal Certified', 'Free Tasting'],
      contactEmail: 'orders@barakabakery.co.uk',
      contactPhone: '+44 116 234 5678',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'mua',
      title: 'Nikkah Glow Beauty',
      location: 'Manchester, UK',
      priceRange: '£££',
      description: 'Luxury bridal beauty services with a focus on South Asian and Middle Eastern brides.',
      bio: 'Nikkah Glow Beauty offers premium bridal beauty services tailored to Muslim brides. Our artists are experts in long-lasting looks that photograph beautifully and last from Nikkah to Walima.',
      specialty: 'Luxury Bridal Beauty',
      sisterFriendly: true,
      features: ['Luxury Products', 'Airbrush Makeup', 'Lash Application', 'Touch-Up Kit'],
      contactEmail: 'book@nikkahglow.co.uk',
      contactPhone: '+44 7700 900234',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'dj',
      title: 'Anasheed Live',
      location: 'Birmingham, UK',
      priceRange: '£££',
      description: 'Premium live nasheed performers and halal entertainment for weddings.',
      bio: 'Anasheed Live brings world-class nasheed artists to your celebration. Our roster includes nationally recognised performers who create an unforgettable atmosphere while keeping everything halal.',
      specialty: 'Live Nasheed Performance',
      features: ['Live Band', 'MC Services', 'Professional Sound', 'Lighting Package'],
      contactEmail: 'bookings@anasheedlive.co.uk',
      contactPhone: '+44 121 567 8901',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'decorator',
      title: 'Arabesque Styling',
      location: 'London, UK',
      priceRange: '£££',
      description: 'Luxury venue transformations with elegant Islamic-inspired design.',
      bio: 'Arabesque Styling specialises in high-end venue transformations for Muslim weddings. Our signature style blends traditional Islamic motifs with modern luxury — think gold calligraphy panels, cascading floral arches, and bespoke stage designs.',
      specialty: 'Luxury Venue Styling',
      features: ['Full Venue Transformation', 'Calligraphy Backdrops', 'Floral Arches', 'Luxury Table Settings'],
      contactEmail: 'hello@arabesquestyling.co.uk',
      contactPhone: '+44 20 7123 4567',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'mua',
      title: 'Modest Beauty Bar',
      location: 'Birmingham, UK',
      priceRange: '££',
      description: 'All-female bridal beauty team offering makeup, hair, and henna services.',
      bio: 'Modest Beauty Bar is a sisters-only salon with a mobile bridal team. We understand the needs of Muslim brides — from long-lasting makeup that holds through a full day of celebrations to expert dupatta and hijab draping.',
      specialty: 'Bridal Hair & Makeup',
      sisterFriendly: true,
      features: ['Sisters Only', 'Henna Services', 'Dupatta Styling', 'Bridal Party Packages'],
      contactEmail: 'book@modestbeautybar.co.uk',
      contactPhone: '+44 121 890 1234',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'dj',
      title: 'Halal Hype Events',
      location: 'Manchester, UK',
      priceRange: '££',
      description: 'Modern halal entertainment with clean music, daff drummers, and interactive games.',
      bio: 'Halal Hype Events brings the energy without compromising your values. Our team provides clean music DJing, live daff performances, interactive games for guests, and professional MC services to keep your reception lively and memorable.',
      specialty: 'Halal Event Entertainment',
      features: ['Clean Music DJ', 'Daff Drummers', 'Interactive Games', 'MC & Host'],
      contactEmail: 'info@halalhypeevents.co.uk',
      contactPhone: '+44 161 345 6789',
    },
  ];

  const allItems = [...venues, ...vendors].map((item) => ({
    section: item.section,
    vendorCategory: item.vendorCategory,
    title: item.title,
    location: item.location ?? null,
    priceRange: item.priceRange ?? null,
    description: item.description ?? null,
    bio: 'bio' in item ? item.bio ?? null : null,
    capacity: 'capacity' in item ? item.capacity ?? null : null,
    sisterFriendly: 'sisterFriendly' in item ? item.sisterFriendly ?? null : null,
    parking: 'parking' in item ? item.parking ?? null : null,
    disabilityAccessible: 'disabilityAccessible' in item ? item.disabilityAccessible ?? null : null,
    features: 'features' in item ? (item.features as string[]) : [],
    amenities: 'amenities' in item ? (item.amenities as string[]) : [],
    specialty: 'specialty' in item ? item.specialty ?? null : null,
    contactEmail: 'contactEmail' in item ? item.contactEmail ?? null : null,
    contactPhone: 'contactPhone' in item ? item.contactPhone ?? null : null,
    source: 'seed',
    status: 'active',
  }));

  await db.insert(vendorItems).values(allItems);
}
