import { sql } from 'drizzle-orm';
import { db } from './db';
import { vendorItems } from './db/schema';

export async function seedDirectory() {
  // Idempotent: skip if already seeded
  const existing = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(vendorItems);

  if ((existing[0]?.count ?? 0) > 0) {
    return;
  }

  const venues = [
    {
      section: 'venue' as const,
      vendorCategory: 'Banquet Hall',
      title: 'Al-Noor Banquet Hall',
      location: 'Chicago, IL',
      priceRange: '$$$',
      description: 'Elegant banquet hall with a capacity of 500 guests, perfect for large Nikkah ceremonies.',
      capacity: '500',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Stage', 'Sound System', 'Lighting'],
      amenities: ['Kitchen', 'Parking Lot', 'Wheelchair Ramp'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Mosque',
      title: 'Islamic Center of Greater Houston',
      location: 'Houston, TX',
      priceRange: '$',
      description: 'Beautiful mosque venue with separate prayer halls for a traditional Nikkah ceremony.',
      capacity: '300',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Prayer Hall', 'Courtyard'],
      amenities: ['Wudu Area', 'Parking'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Hotel',
      title: 'The Grand Marquis',
      location: 'New York, NY',
      priceRange: '$$$$',
      description: 'Luxury hotel ballroom with stunning chandeliers and premium catering.',
      capacity: '400',
      sisterFriendly: false,
      parking: true,
      disabilityAccessible: true,
      features: ['Ballroom', 'Bridal Suite', 'Valet Parking'],
      amenities: ['Full Kitchen', 'AV Equipment', 'Coat Check'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Community Center',
      title: 'Ummah Community Center',
      location: 'Dearborn, MI',
      priceRange: '$$',
      description: 'Spacious community center in the heart of Dearborn, accommodating up to 350 guests.',
      capacity: '350',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Main Hall', 'Kitchen Access', 'Stage'],
      amenities: ['Tables & Chairs', 'Sound System'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Banquet Hall',
      title: 'Crescent Moon Events',
      location: 'Dallas, TX',
      priceRange: '$$$',
      description: 'Modern event space with customizable lighting and decor packages.',
      capacity: '250',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['LED Lighting', 'Dance Floor', 'Lounge Area'],
      amenities: ['In-House Catering', 'Valet'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Garden',
      title: 'Rose Garden Estate',
      location: 'Los Angeles, CA',
      priceRange: '$$$$',
      description: 'Beautiful outdoor garden venue ideal for spring and summer celebrations.',
      capacity: '200',
      sisterFriendly: false,
      parking: true,
      disabilityAccessible: false,
      features: ['Garden Setting', 'Fountain', 'Pergola'],
      amenities: ['Tent Rental', 'Parking'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Banquet Hall',
      title: 'Salam Palace',
      location: 'Atlanta, GA',
      priceRange: '$$',
      description: 'Affordable banquet hall with halal catering options included.',
      capacity: '300',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Stage', 'Projector Screen'],
      amenities: ['Halal Kitchen', 'Free Parking'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Hotel',
      title: 'Hilton Downtown Convention',
      location: 'San Francisco, CA',
      priceRange: '$$$$',
      description: 'Premium downtown hotel with multiple ballroom options.',
      capacity: '600',
      sisterFriendly: false,
      parking: true,
      disabilityAccessible: true,
      features: ['Multiple Rooms', 'Bridal Suite', 'Bar Area'],
      amenities: ['Full Catering', 'AV', 'Valet'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Mosque',
      title: 'Masjid Al-Huda',
      location: 'Philadelphia, PA',
      priceRange: '$',
      description: 'Welcoming mosque with a large community hall for intimate ceremonies.',
      capacity: '150',
      sisterFriendly: true,
      parking: false,
      disabilityAccessible: true,
      features: ['Community Hall', 'Kitchen'],
      amenities: ['Wudu Facilities'],
    },
    {
      section: 'venue' as const,
      vendorCategory: 'Community Center',
      title: 'Al-Iman Cultural Center',
      location: 'Minneapolis, MN',
      priceRange: '$$',
      description: 'Cultural center with flexible spaces for wedding events.',
      capacity: '250',
      sisterFriendly: true,
      parking: true,
      disabilityAccessible: true,
      features: ['Large Hall', 'Breakout Rooms'],
      amenities: ['Sound System', 'Projector'],
    },
  ];

  const vendors = [
    {
      section: 'vendor' as const,
      vendorCategory: 'Photographer',
      title: 'Noor Photography',
      location: 'New York, NY',
      priceRange: '$$$',
      description: 'Specializing in elegant Muslim wedding photography with a focus on modesty.',
      specialty: 'Muslim Wedding Photography',
      sisterFriendly: true,
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Caterer',
      title: 'Bismillah Catering',
      location: 'Chicago, IL',
      priceRange: '$$',
      description: 'Premium halal catering with South Asian, Middle Eastern, and fusion menus.',
      specialty: 'Halal Catering',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Florist',
      title: 'Zahra Floral Design',
      location: 'Houston, TX',
      priceRange: '$$',
      description: 'Custom floral arrangements inspired by Islamic geometric patterns.',
      specialty: 'Wedding Florals',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'DJ / Entertainment',
      title: 'Nasheed Beats Entertainment',
      location: 'Dallas, TX',
      priceRange: '$$',
      description: 'Halal entertainment with nasheeds, live daff, and clean music DJing.',
      specialty: 'Islamic Entertainment',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Videographer',
      title: 'Barakah Films',
      location: 'Los Angeles, CA',
      priceRange: '$$$',
      description: 'Cinematic wedding films capturing every beautiful moment of your nikkah.',
      specialty: 'Wedding Videography',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Makeup Artist',
      title: 'Hijabi Glam Studio',
      location: 'Dearborn, MI',
      priceRange: '$$',
      description: 'Bridal makeup and hijab styling for your perfect day.',
      specialty: 'Bridal Makeup & Hijab Styling',
      sisterFriendly: true,
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Caterer',
      title: 'Saffron & Spice Catering',
      location: 'San Francisco, CA',
      priceRange: '$$$',
      description: 'Upscale halal catering featuring diverse international cuisines.',
      specialty: 'International Halal Cuisine',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Photographer',
      title: 'Amanah Studios',
      location: 'Atlanta, GA',
      priceRange: '$$',
      description: 'Photography and photo booth services for Muslim weddings.',
      specialty: 'Event Photography',
      sisterFriendly: true,
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Decorator',
      title: 'Henna & Drapes Decor',
      location: 'Houston, TX',
      priceRange: '$$',
      description: 'Full event styling with draping, centerpieces, and henna-themed decor.',
      specialty: 'Wedding Decor',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Cake / Desserts',
      title: 'Baraka Bakery',
      location: 'Philadelphia, PA',
      priceRange: '$$',
      description: 'Custom wedding cakes and dessert tables, all halal certified.',
      specialty: 'Halal Wedding Cakes',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Officiant',
      title: 'Imam Services Network',
      location: 'Multiple Locations',
      priceRange: '$',
      description: 'Certified Imams available for nikkah ceremonies across the US.',
      specialty: 'Nikkah Officiation',
    },
    {
      section: 'vendor' as const,
      vendorCategory: 'Invitation Design',
      title: 'Calligraphy & Co',
      location: 'Online',
      priceRange: '$$',
      description: 'Custom Arabic calligraphy wedding invitations and stationery.',
      specialty: 'Arabic Calligraphy Invitations',
    },
  ];

  const allItems = [...venues, ...vendors].map((item) => ({
    section: item.section,
    vendorCategory: item.vendorCategory,
    title: item.title,
    location: item.location ?? null,
    priceRange: item.priceRange ?? null,
    description: item.description ?? null,
    capacity: 'capacity' in item ? item.capacity ?? null : null,
    sisterFriendly: 'sisterFriendly' in item ? item.sisterFriendly ?? null : null,
    parking: 'parking' in item ? item.parking ?? null : null,
    disabilityAccessible: 'disabilityAccessible' in item ? item.disabilityAccessible ?? null : null,
    features: 'features' in item ? (item.features as string[]) : [],
    amenities: 'amenities' in item ? (item.amenities as string[]) : [],
    specialty: 'specialty' in item ? item.specialty ?? null : null,
    source: 'seed',
    status: 'active',
  }));

  await db.insert(vendorItems).values(allItems);
}
